Repository fury-gl/fury, pull requests merged in 2018-12, with the labels that each got.

#30 Add doc generation on Travis
  .travis.yml
  CONTRIBUTING.rst
  ci/travis/deploy_docs.sh
  ci/travis/install.sh
  ci/travis/script.sh
  docs/README.md
  docs/make.bat
  docs/upload_to_gh-pages.py
  requirements/README.md
  requirements/docs.txt
Labels: state: needs a code review, state: ready-to-be-merged, type:Maintenance

#21 Add depth_cue and fake_tube to simulate tubes with lines
  .gitignore
  MANIFEST.in
  docs/examples/viz_bundles.py
  fury/actor.py
  fury/shaders/__init__.py
  fury/shaders/line.geom
  fury/tests/test_actors.py
  fury/tests/test_shaders.py
  setup.py
Labels: state: ready-to-be-merged, type:New Feature

#39 removing widget module
  fury/tests/test_widgets.py
  fury/widget.py
Labels: state: needs review, state: ready-to-be-merged, type:Maintenance
