Repository fury-gl/fury, pull requests merged in 2019-12, with the labels that each got.

#128 Update Deprecated function
  azure-pipelines.yml
  fury/tests/test_window.py
  fury/window.py
Labels: type:Maintenance

#130 Adding Sphere primitives
  fury/data/files/evenly_distributed_sphere_362.npz
  fury/data/files/evenly_distributed_sphere_642.npz
  fury/data/files/evenly_distributed_sphere_724.npz
  fury/data/files/repulsion100.npz
  fury/data/files/repulsion200.npz
  fury/data/files/repulsion724.npz
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
  fury/tests/test_ui.py
Labels: type:New Feature

#131 Add Superquadric primitives and actors
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
  fury/tests/test_transform.py
  fury/transform.py
  fury/utils.py
Labels: type:New Feature

#129 update loading and saving IO for polydata
  fury/actor.py
  fury/io.py
  fury/tests/test_io.py
  fury/utils.py
Labels: type:Enhancement

#134 Add event parameter on add_window_callback method in ShowManager class.
  fury/window.py
Labels: type:Enhancement
