Repository fury-gl/fury, pull requests merged in 2019-03, with the labels that each got.

#50 [NF] Doc version
  CONTRIBUTING.rst
  docs/examples/viz_roi_contour.py
  docs/source/_static/css/custom_github.css
  docs/source/_static/css/fury.css
  docs/source/_static/images/commits.png
  docs/source/_static/images/contributors.png
  docs/source/_static/images/forks.png
  docs/source/_static/images/stars.png
  docs/source/_templates/page.html
  docs/source/_templates/versions.html
  docs/source/authors_link.rst
  docs/source/conf.py
  docs/source/contributors.json
  docs/source/ext/apigen.py
  docs/source/ext/build_modref_templates.py
  docs/source/ext/github_tools.py
  docs/source/ext/rstjinja.py
Labels: state: needs review, type:Documentation

#55 Add stereo rendering support
  fury/tests/test_window.py
  fury/window.py
Labels: state: needs review, type:New Feature

#31 new surface function
  fury/actor.py
  fury/tests/test_actors.py
Labels: state: work-in-progress, type:New Feature
