Repository fury-gl/fury, pull requests merged in 2019-09, with the labels that each got.

#97 Bug fix for double slider
  fury/ui.py
  fury/window.py
Labels: state: ready-to-be-merged, type:Bug Fix

#98 [Fix] layout with small cells
  fury/tests/test_utils.py
  fury/utils.py
Labels: state: needs review, type:Bug Fix

#102 from assert to npt_assert_equal
  fury/tests/test_ui.py
  fury/tests/test_window.py
Labels: type:Maintenance

#101 Update travis
  .travis.yml
  README.rst
  ci/travis/deploy_docs.sh
  ci/travis/install.sh
  ci/travis/script.sh
  docs/source/installation.rst
  fury/decorators.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_ui.py
  fury/tests/test_utils.py
  fury/tests/test_window.py
  requirements/default.txt
Labels: state: ready-to-be-merged, type:Maintenance

#103 Remove nose dependency
  docs/examples/viz_advanced.py
  docs/examples/viz_roi_contour.py
  docs/source/ext/apigen.py
  docs/source/ext/build_modref_templates.py
  fury/data/fetcher.py
  fury/io.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_ui.py
  fury/tests/test_window.py
  requirements/test.txt
Labels: state: ready-to-be-merged, type:Maintenance

#105 Replacing appveyor by Azure
  azure-pipelines.yml
  ci/appveyor/script.ps1
  ci/windows/appveyor.yml
  ci/windows/install.ps1
  ci/windows/install_opengl.ps1
  ci/windows/run_with_env.cmd
  ci/windows/script.ps1
  fury/actor.py
  fury/decorators.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_ui.py
  fury/tests/test_window.py
  fury/window.py
Labels: type:Maintenance

#104 Made it simpler to change color in ListBox
  fury/tests/test_ui.py
  fury/ui.py
Labels: state: work-in-progress, type:Enhancement

#106 [Fix] doc generation
  README.rst
  docs/examples/viz_advanced.py
  docs/source/conf.py
Labels: type:Bug Fix, type:Maintenance

#107 Increase coverage for test_actors
  docs/source/ext/github_tools.py
  fury/actor.py
  fury/data/fetcher.py
  fury/optpkg.py
  fury/tests/test_actors.py
  fury/tests/test_optpkg.py
  fury/tests/test_ui.py
  fury/ui.py
Labels: state: ready-to-be-merged, type:Maintenance
