Repository fury-gl/fury, pull requests merged in 2019-04, with the labels that each got.

#62 Directional color odfs
  fury/actor.py
  fury/tests/test_actors.py
Labels: state: ready-to-be-merged, type:New Feature

#67 [Fix] Update doc management
  docs/source/_templates/versions.html
  docs/source/ext/github.py
  docs/source/ext/github_tools.py
Labels: type:Documentation, type:Maintenance

#68 Allow Str for Grid Caption
  fury/actor.py
  fury/tests/test_actors.py
Labels: state: needs review, type:Enhancement
