Repository fury-gl/fury, pull requests merged in 2019-07, with the labels that each got.

#83 Remove issue template
  .gitignore
  ISSUE_TEMPLATE.md
Labels: type:Maintenance

#86 Fixes a typo in the viz_ui tutorial.
  docs/tutorials/viz_ui.py
  requirements/default.txt
Labels: state: ready-to-be-merged, type:Maintenance

#69 Add middle button callback
  fury/tests/test_ui.py
  fury/ui.py
Labels: state: needs review, type:Enhancement

#89 [Fix] cmap when not have matplotlib
  fury/colormap.py
  fury/tests/test_colormap.py
Labels: state: needs review, type:Maintenance

#53 [Fix] resolution limit
  fury/io.py
  fury/tests/test_io.py
  fury/tests/test_window.py
  fury/window.py
Labels: state: needs review, type:Bug Fix
