Repository fury-gl/fury, pull requests merged in 2019-02, with the labels that each got.

#32 The grid - add actors in a grid and interact with each one of them independently
  .travis.yml
  fury/actor.py
  fury/colormap.py
  fury/data/files/test_grid_ui.log.gz
  fury/data/files/test_grid_ui.pkl
  fury/interactor.py
  fury/layout.py
  fury/tests/test_actors.py
  fury/tests/test_ui.py
  fury/tests/test_utils.py
  fury/ui.py
  fury/utils.py
  fury/window.py
Labels: type:New Feature

#56 Increase Codacy rank
  ISSUE_TEMPLATE.md
  docs/README.md
  docs/examples/viz_advanced.py
  docs/examples/viz_surfaces.py
  docs/source/ext/apigen.py
  docs/tutorials/viz_slice.py
  docs/tutorials/viz_timers.py
  docs/tutorials/viz_ui.py
  docs/upload_to_gh-pages.py
  fury/actor.py
  fury/colormap.py
  fury/interactor.py
  fury/layout.py
  fury/testing.py
  fury/tests/test_actors.py
  fury/tests/test_colormap.py
  fury/tests/test_interactor.py
  fury/tests/test_testing.py
  fury/tests/test_ui.py
  fury/tests/test_utils.py
  fury/tmpdirs.py
  fury/ui.py
  fury/window.py
Labels: type:Maintenance

#52 [Fix] add filterwarnings
  fury/__init__.py
Labels: state: needs review, type:Maintenance

#57 Add tests to utils module
  fury/tests/test_utils.py
  fury/utils.py
Labels: state: needs review, type:Maintenance

#58 Tests addition
  fury/colormap.py
  fury/tests/test_colormap.py
  fury/tests/test_decorators.py
  fury/tests/test_optpkg.py
Labels: state: needs review, type:Maintenance

#59 [NF] Add get_info function
  fury/__init__.py
  fury/tests/test_optpkg.py
Labels: state: needs review, type:New Feature

#60 backward compatibilities
  fury/window.py
Labels: state: needs review, type:Maintenance
