Repository fury-gl/fury, pull requests merged in 2019-01, with the labels that each got.

#42 [Fix] viz_surface
  docs/examples/viz_surfaces.py
  fury/io.py
  fury/tests/test_io.py
Labels: state: ready-to-be-merged, type:Bug Fix

#44 BUG: Fix elementwise comparison deprecation warning.
  fury/window.py
Labels: state: needs review, type:Maintenance

#43 BUG: Fix `peaks_slicer` actor properties not being enforced.
  fury/actor.py
Labels: state: needs review, type:Bug Fix

#48 ENH: Exercise the `PeakSlicerActor` `opacity` explicitly.
  fury/tests/test_actors.py
Labels: state: needs review, type:Enhancement

#47 BUG: Fix `TensorSlicerActor` actor opacity property not being enforced.
  fury/actor.py
  fury/tests/test_actors.py
Labels: state: needs review, type:Bug Fix
