Repository fury-gl/fury, pull requests merged in 2019-10, with the labels that each got.

#112 Use glyph for several actors
  fury/actor.py
  fury/tests/test_actors.py
  fury/tests/test_window.py
  fury/utils.py
Labels: state: needs review, type:New Feature

#109 Show frame rate and enable anti-aliasing
  fury/tests/test_ui.py
  fury/window.py
Labels: type:New Feature

#115 Release 0.4.0 preparation
  .gitignore
  .mailmap
  CONTRIBUTING.rst
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.3.0.rst
  docs/source/release_notes/releasev0.4.0.rst
  docs/tutorials/viz_slice.py
  fury/actor.py
  fury/window.py
  requirements/docs.txt
Labels: type:Release Plan
