Repository fury-gl/fury, pull requests merged in 2020-09, with the labels that each got.

#306 merged basic UI and advanced UI tutorials into one
  docs/tutorials/02_ui/README.rst
  docs/tutorials/02_ui/viz_buttons.py
  docs/tutorials/02_ui/viz_check_boxes.py
  docs/tutorials/02_ui/viz_combobox.py
  docs/tutorials/02_ui/viz_radio_buttons.py
  docs/tutorials/02_ui/viz_shapes.py
  docs/tutorials/02_ui/viz_tab.py
  docs/tutorials/02_ui/viz_ui.py
  docs/tutorials/02_ui/viz_ui_listbox.py
  docs/tutorials/02_ui/viz_ui_slider.py
  docs/tutorials/03_advanced_ui/README.rst
  docs/tutorials/03_shaders/README.rst
  docs/tutorials/03_shaders/viz_sdfactor.py
  docs/tutorials/03_shaders/viz_shader.py
Labels: type:Documentation

#304 Blogs for the final review
  docs/source/posts/2020/2020-08-09-week-11-lenix.rst
  docs/source/posts/2020/2020-08-17-week-12-lenix.rst
  docs/source/posts/2020/2020-08-24-final-work-lenix.rst
  docs/source/posts/2020/2020-08-24-week-13-lenix.rst
Labels: :rocket: :snake: GSOC 2020, type:Documentation

#307 Fixed translating and scaling issues on billboard and SDF actors
  fury/actor.py
  fury/shaders/billboard_dec.frag
  fury/shaders/billboard_dec.vert
  fury/shaders/billboard_impl.frag
  fury/shaders/billboard_impl.vert
  fury/tests/test_actors.py
Labels: type:Bug Fix

#311 Remove python35 from Travis
  .travis.yml
  docs/examples/physics_using_pybullet/viz_brick_wall.py
  docs/source/posts/2020/2020-07-05-week-6-soham.rst
  docs/source/posts/2020/2020-08-24-final-work-lenix.rst
  docs/source/posts/2020/2020-08-24-week-13-lenix.rst
  docs/tutorials/01_introductory/viz_earth_coordinates.py
  fury/deprecator.py
Labels: type:Documentation, type:Maintenance
