Repository fury-gl/fury, pull requests merged in 2020-03, with the labels that each got.

#165 Vertical Layout for LineSlider2D
  docs/tutorials/viz_ui.py
  fury/data/files/test_ui_line_slider_2d_horizontal.json
  fury/data/files/test_ui_line_slider_2d_horizontal.log.gz
  fury/data/files/test_ui_line_slider_2d_vertical.json
  fury/data/files/test_ui_line_slider_2d_vertical.log.gz
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:Enhancement

#167 Animated Network Visualization Example
  docs/examples/viz_network_animated.py
  requirements/docs.txt
Labels: type:Documentation

#173 Fixing Text Overflow of ListBox2D
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:Bug Fix

#191 DOC: Fix `actor.line` parameter type and add `optional` keyword
  fury/actor.py
Labels: type:Documentation

#177 [Fix] Flipping during save
  fury/io.py
  fury/tests/test_io.py
  fury/window.py
Labels: type:Bug Fix

#182 [Doc] Reshape the documentation
  CONTRIBUTING.rst
  docs/Makefile
  docs/examples/README.rst
  docs/make.bat
  docs/source/_templates/page.html
  docs/source/_templates/versions.html
  docs/source/community.rst
  docs/source/conf.py
  docs/source/contributing_link.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/symlink/contributing.rst
  docs/source/symlink/license.rst
  docs/source/usage.rst
  docs/tutorials/01_ui/README.rst
  docs/tutorials/01_ui/viz_buttons.py
  docs/tutorials/01_ui/viz_shapes.py
  docs/tutorials/01_ui/viz_ui_listbox.py
  docs/tutorials/01_ui/viz_ui_slider.py
  docs/tutorials/02_advanced_ui/README.rst
  docs/tutorials/02_advanced_ui/viz_ui.py
  docs/tutorials/03_shaders/README.rst
  docs/tutorials/03_shaders/viz_shader.py
  docs/tutorials/04_others/README.rst
  docs/tutorials/04_others/viz_slice.py
  docs/tutorials/04_others/viz_spiky.py
  docs/tutorials/04_others/viz_surfaces.py
  docs/tutorials/04_others/viz_timers.py
  fury/tests/__init__.py
  fury/tests/test_io.py
  fury/tests/test_shaders.py
  fury/tests/test_testing.py
  fury/tests/test_ui.py
  fury/tests/test_utils.py
  fury/tests/test_window.py
  requirements/docs.txt
  requirements/optional.txt
  requirements/test.txt
Labels: type:Documentation

#194 [FIX] Update superquadrics test
  docs/tutorials/03_shaders/viz_shader.py
  fury/tests/test_actors.py
Labels: type:Maintenance

#189 Added dynamic text positioning
  docs/tutorials/01_ui/viz_ui_slider.py
  fury/data/files/test_ui_line_slider_2d_horizontal_bottom.json
  fury/data/files/test_ui_line_slider_2d_horizontal_bottom.log.gz
  fury/data/files/test_ui_line_slider_2d_horizontal_top.json
  fury/data/files/test_ui_line_slider_2d_horizontal_top.log.gz
  fury/data/files/test_ui_line_slider_2d_vertical_left.json
  fury/data/files/test_ui_line_slider_2d_vertical_left.log.gz
  fury/data/files/test_ui_line_slider_2d_vertical_right.json
  fury/data/files/test_ui_line_slider_2d_vertical_right.log.gz
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:Enhancement

#192 Tetrahedron, Icosahedron primitives
  fury/primitive.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#198 Utils test and winding order algorithm
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:New Feature

#181 Vertical Layout for LineDoubleSlider2D
  fury/tests/test_ui.py
  fury/ui.py
Labels: state: ready-to-be-merged, type:Enhancement

#201 [FIX] icons flipping
  fury/io.py
Labels: type:Bug Fix

#190 Add initial state to checkbox
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:Enhancement

#204 Vertical Layout for RangeSlider
  docs/tutorials/02_advanced_ui/viz_ui.py
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:New Feature

#203 Namanb009 windowtitlefix
  fury/window.py
Labels: type:Bug Fix

#206 [FIX] avoid in-place replacements
  docs/tutorials/01_ui/viz_ui_slider.py
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:Enhancement

#207 updated fetcher
  fury/data/fetcher.py
Labels: type:New Feature

#215 Remove more than one actors at once
  fury/window.py
Labels: type:Enhancement

#213 Utils vtk
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:New Feature

#220 bumping scipy version to 1.2.0
  requirements/default.txt
Labels: type:Maintenance

#218 Changed options attribute from list to dict and updated respective tests
  fury/tests/test_ui.py
  fury/ui.py
  fury/window.py
Labels: type:Enhancement
