Repository fury-gl/fury, pull requests merged in 2020-07, with the labels that each got.

#233 Picking API and picking tutorial
  docs/tutorials/01_introductory/viz_picking.py
  fury/pick.py
  fury/tests/test_pick.py
  fury/utils.py
Labels: type:New Feature

#255 Let VTK delete timers on exit.
  fury/decorators.py
  fury/deprecator.py
  fury/tests/test_window.py
  fury/window.py
  requirements/default.txt
  setup.py
Labels: type:Bug Fix

#127 [CI] add Python 3.8
  .mailmap
  .travis.yml
  azure-pipelines.yml
  fury/tests/test_deprecator.py
  fury/tests/test_pick.py
  fury/ui.py
Labels: type:Maintenance

#263 [NF] Deprecated parameters
  fury/deprecator.py
  fury/tests/test_deprecator.py
Labels: type:New Feature

#248 Setting Bounding Box for TextBlock2D
  docs/examples/viz_advanced.py
  fury/tests/test_ui.py
  fury/ui.py
Labels: :rocket: :snake: GSOC 2020

#262 Solar System Tutorial
  docs/tutorials/01_introductory/viz_solar_system.py
  fury/data/fetcher.py
Labels: type:Documentation

#169 Use primitive for box, cube, square, rectangle actors
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_utils.py
  fury/tests/test_window.py
Labels: type:Enhancement

#240 ComboBox2D UI element
  fury/data/files/test_ui_combobox_2d.json
  fury/data/files/test_ui_combobox_2d.log.gz
  fury/tests/test_ui.py
  fury/ui.py
Labels: :rocket: :snake: GSOC 2020, state: work-in-progress

#265 Adding new Earth coordinates tutorial
  docs/tutorials/01_introductory/viz_earth_coordinates.py
  fury/data/fetcher.py
Labels: type:Documentation

#246 ComboBox UI tutorial
  docs/tutorials/02_ui/viz_combobox.py
Labels: :rocket: :snake: GSOC 2020, state: work-in-progress, type:Documentation

#250 SDF based FURY actors
  docs/experimental/viz_multisdf.py
  fury/actor.py
  fury/shaders/sdf_dec.frag
  fury/shaders/sdf_dec.vert
  fury/shaders/sdf_impl.frag
  fury/shaders/sdf_impl.vert
  fury/shaders/sdfmulti_dec.frag
  fury/shaders/sdfmulti_impl.frag
  fury/tests/test_actors.py
Labels: :rocket: :snake: GSOC 2020, state: work-in-progress, type:New Feature

#267 SDF tutorial
  docs/tutorials/04_shaders/viz_sdfactor.py
Labels: :rocket: :snake: GSOC 2020, type:Documentation

#268 Clip Text Overflow
  fury/tests/test_ui.py
  fury/ui.py
Labels: :rocket: :snake: GSOC 2020, type:Bug Fix, type:New Feature

#241 Adding a Blog system to fury
  docs/source/_static/css/blog.css
  docs/source/_static/versions.json
  docs/source/_templates/page.html
  docs/source/blog.rst
  docs/source/community.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/posts/2018/2018-09-21-release-announcement.rst
  docs/source/posts/2018/2018-10-31-release-announcement.rst
  docs/source/posts/2018/2018-11-26-release-announcement.rst
  docs/source/posts/2019/2019-03-08-release-announcement.rst
  docs/source/posts/2019/2019-06-19-brain-art.rst
  docs/source/posts/2019/2019-08-02-release-announcement.rst
  docs/source/posts/2019/2019-10-29-release-announcement.rst
  docs/source/posts/2019/Melpomene_Brain-Streamlines-shader-experiment_by_David-Reagan.jpg
  docs/source/posts/2020/2020-01-05-gsoc.rst
  docs/source/posts/2020/2020-04-09-release-announcement.rst
  fury/deprecator.py
  requirements/docs.txt
Labels: type:Documentation

#266 Release 0.6.0 preparation
  .mailmap
  AUTHORS.rst
  docs/source/ext/github_tools.py
  docs/source/posts/2020/2020-07-20-release-announcement.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.6.0.rst
  setup.py
Labels: type:Release Plan
