Repository fury-gl/fury, pull requests merged in 2020-06, with the labels that each got.

#244 Added new texture tutorial
  docs/tutorials/01_introductory/viz_texture.py
  fury/data/__init__.py
  fury/data/fetcher.py
Labels: type:Documentation

#245 [FIX] Compatibility with VTK 9
  fury/actor.py
  fury/tests/test_actors.py
  fury/tests/test_window.py
  fury/utils.py
Labels: type:Maintenance

#256 Install ssl certificate for azure pipeline windows
  azure-pipelines.yml
Labels: type:Maintenance

#259 Updated Step 3 in README.rst
  README.rst
Labels: type:Documentation

#258 Updating test of order_transparency for compatibility with vtk 9
  fury/tests/test_window.py
Labels: type:Maintenance

#249 Octagonal Prism and Frustum Square Pyramid
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#261 Adding Earth Animation Tutorial
  docs/tutorials/01_introductory/viz_earth_animation.py
  fury/data/__init__.py
  fury/data/fetcher.py
Labels: type:Documentation
