Repository fury-gl/fury, pull requests merged in 2020-02, with the labels that each got.

#139 [Fix] some docstring for doc generation
  fury/convert.py
  fury/primitive.py
  fury/window.py
Labels: state: needs review, type:Documentation

#144 STYLE: Change examples `README` file extension to reStructuredText
  docs/examples/README.rst
Labels: type:Documentation

#148 updated fetcher.py
  fury/data/fetcher.py
Labels: type:Enhancement

#157 Corrected Disk2D comments
  fury/ui.py
Labels: type:Documentation

#163 Spelling error
  fury/window.py
Labels: type:Documentation

#164 Documentation
  fury/actor.py
Labels: type:Documentation

#132 Add Billboard actor
  docs/experimental/viz_canvas.py
  fury/actor.py
  fury/primitive.py
  fury/shaders/billboard_dec.frag
  fury/shaders/billboard_dec.vert
  fury/shaders/billboard_impl.frag
  fury/shaders/billboard_impl.vert
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
Labels: state: needs review, type:New Feature

#153 Sep viz ui
  docs/tutorials/viz_buttons.py
  docs/tutorials/viz_shapes.py
  docs/tutorials/viz_ui_listbox.py
  docs/tutorials/viz_ui_slider.py
Labels: type:Documentation

#154 Added Shader tutorial
  docs/tutorials/viz_shader.py
  fury/data/fetcher.py
Labels: type:Documentation
