Repository fury-gl/fury, pull requests merged in 2020-04, with the labels that each got.

#223 [Fix] sphere winding issue
  fury/primitive.py
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:Bug Fix

#225 update tutorial folder structure
  docs/tutorials/01_introductory/README.rst
  docs/tutorials/01_introductory/viz_slice.py
  docs/tutorials/01_introductory/viz_spiky.py
  docs/tutorials/01_introductory/viz_surfaces.py
  docs/tutorials/01_introductory/viz_timers.py
  docs/tutorials/02_ui/README.rst
  docs/tutorials/02_ui/viz_buttons.py
  docs/tutorials/02_ui/viz_shapes.py
  docs/tutorials/02_ui/viz_ui_listbox.py
  docs/tutorials/02_ui/viz_ui_slider.py
  docs/tutorials/03_advanced_ui/README.rst
  docs/tutorials/03_advanced_ui/viz_ui.py
  docs/tutorials/04_others/README.rst
  docs/tutorials/04_shaders/README.rst
  docs/tutorials/04_shaders/viz_shader.py
  fury/window.py
Labels: type:Documentation

#210 Added contour_from_label method
  fury/actor.py
  fury/tests/test_actors.py
Labels: type:New Feature

#227 [Fix] update streamlines default color
  README.rst
  fury/actor.py
  fury/utils.py
Labels: type:Bug Fix

#229 Release 0.5.0 preparation
  .mailmap
  AUTHORS.rst
  CONTRIBUTING.rst
  LICENSE
  docs/source/_templates/page.html
  docs/source/community.rst
  docs/source/ext/github_tools.py
  docs/source/index.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.5.0.rst
Labels: type:Release Plan

#232 Improve packaging
  MANIFEST.in
  setup.py
Labels: type:Maintenance

#237 update copyright years
  docs/source/conf.py
Labels: type:Maintenance

#238 Added Rhombocuboctahedron, 2D and 3D star to primitive
  fury/primitive.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#235 Function to use Hexadecimal color code in Colormap
  fury/colormap.py
  fury/tests/test_colormap.py
Labels: type:New Feature
