Repository fury-gl/fury, pull requests merged in 2020-10, with the labels that each got.

#319 fixed discord icon bug in documentation
  docs/source/_templates/page.html
  docs/source/community.rst
Labels: :beer: Hacktoberfest :beer:, type:Documentation

#286 GSoC blogs for Third Evaluation.
  docs/source/posts/2020/2020-08-09-week-11-soham.rst
  docs/source/posts/2020/2020-08-16-week-12-soham.rst
  docs/source/posts/2020/2020-08-23-week-13-soham.rst
  docs/source/posts/2020/2020-08-24-final-work-soham.rst
Labels: :rocket: :snake: GSOC 2020, type:Documentation

#329 [FIX] Force LUT to be RGB
  fury/actor.py
  fury/window.py
Labels: type:Bug Fix

#328 Added cylinder primitive
  fury/primitive.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#332 Fixing UI warnings
  pytest.ini
Labels: state: needs decision, state: needs feedback, type:Discussion, type:Maintenance
