Repository fury-gl/fury, pull requests merged in 2020-11, with the labels that each got.

#334 Added Domino-Simulation-file for Review
  docs/examples/physics_using_pybullet/viz_domino.py
Labels: type:Documentation

#336 Update UI tutorials.
  docs/tutorials/02_ui/viz_buttons.py
  docs/tutorials/02_ui/viz_check_boxes.py
  docs/tutorials/02_ui/viz_combobox.py
  docs/tutorials/02_ui/viz_radio_buttons.py
  docs/tutorials/02_ui/viz_shapes.py
  docs/tutorials/02_ui/viz_tab.py
  docs/tutorials/02_ui/viz_ui.py
  docs/tutorials/02_ui/viz_ui_listbox.py
  docs/tutorials/02_ui/viz_ui_slider.py
Labels: type:Maintenance

#337 Add support for clipping side in clip_overflow_text
  fury/tests/test_ui.py
  fury/ui.py
Labels: type:Enhancement

#340 Pass OAuth token through header
  docs/source/ext/github_tools.py
Labels: type:Enhancement

#339 Update Readme informations
  README.md
  README.rst
  docs/source/ext/github_tools.py
  setup.py
Labels: type:Enhancement
