Repository fury-gl/fury, pull requests merged in 2020-08, with the labels that each got.

#272 Python GSoC Blogs upto 19th July 2020
  docs/source/posts/2020/2020-05-30-week-1-soham.rst
  docs/source/posts/2020/2020-06-07-week-2-soham.rst
  docs/source/posts/2020/2020-06-14-week-3-soham.rst
  docs/source/posts/2020/2020-06-21-week-4-soham.rst
  docs/source/posts/2020/2020-06-28-week-5-soham.rst
  docs/source/posts/2020/2020-07-05-week-6-soham.rst
  docs/source/posts/2020/2020-07-12-week-7-soham.rst
  docs/source/posts/2020/2020-07-19-week-8-soham.rst
  docs/source/posts/2020/2020-07-26-week-9-soham.rst
  docs/source/posts/2020/2020-08-02-week-10-soham.rst
Labels: :rocket: :snake: GSOC 2020, state: needs feedback, type:Documentation

#276 Update Deprecated test
  fury/tests/test_deprecator.py
  fury/tests/test_window.py
Labels: type:Maintenance

#273 Python GSoC Weekly blogs
  docs/source/posts/2020/2020-05-30-week-1-lenix.rst
  docs/source/posts/2020/2020-06-07-week-2-lenix.rst
  docs/source/posts/2020/2020-06-14-week-3-lenix.rst
  docs/source/posts/2020/2020-06-21-week-4-lenix.rst
  docs/source/posts/2020/2020-06-28-week-5-lenix.rst
  docs/source/posts/2020/2020-07-05-week-6-lenix.rst
  docs/source/posts/2020/2020-07-13-week-7-lenix.rst
  docs/source/posts/2020/2020-07-20-week-8-lenix.rst
  docs/source/posts/2020/2020-07-27-week-9-lenix.rst
  docs/source/posts/2020/2020-08-02-week-10-lenix.rst
Labels: :rocket: :snake: GSOC 2020, type:Documentation

#252 Tab ui
  fury/data/files/test_ui_tab_ui.json
  fury/data/files/test_ui_tab_ui.log.gz
  fury/tests/test_ui.py
  fury/ui.py
Labels: :rocket: :snake: GSOC 2020, state: work-in-progress, type:New Feature

#282 Standardize Colors array name
  fury/actor.py
  fury/utils.py
Labels: type:Bug Fix

#283 Standardize colors across API
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
  fury/tests/test_utils.py
  fury/tests/test_window.py
  fury/utils.py
  fury/window.py
Labels: type:Bug Fix

#281 Radio checkbox tutorial using Fury API
  docs/tutorials/02_ui/viz_check_boxes.py
  docs/tutorials/02_ui/viz_radio_buttons.py
Labels: type:Documentation

#208 Added tutorial for RadioButton and CheckBox UI
  docs/tutorials/02_ui/viz_check_boxes.py
  docs/tutorials/02_ui/viz_radio_buttons.py
Labels: type:Documentation

#275 Tab UI tutorial
  docs/tutorials/02_ui/viz_tab.py
Labels: :rocket: :snake: GSOC 2020, type:Documentation

#284 Colliding particles in the box
  docs/examples/collision-particles.py
Labels: type:Documentation

#287 Add Physics simulation examples.
  docs/experimental/viz_beads.py
  docs/experimental/viz_brick_wall.py
  docs/experimental/viz_rope.py
  docs/tutorials/05_physics/viz_ball_collide.py
  docs/tutorials/05_physics/viz_brick_wall.py
  docs/tutorials/05_physics/viz_chain.py
  docs/tutorials/05_physics/viz_wrecking_ball.py
Labels: :rocket: :snake: GSOC 2020, type:Documentation, type:New Feature

#289 Rename parameter scale to scales
  docs/examples/collision-particles.py
  docs/experimental/viz_brick_wall.py
  docs/experimental/viz_multisdf.py
  docs/tutorials/02_ui/viz_check_boxes.py
  docs/tutorials/02_ui/viz_tab.py
  docs/tutorials/04_shaders/viz_sdfactor.py
  docs/tutorials/05_physics/viz_brick_wall.py
  docs/tutorials/05_physics/viz_chain.py
  docs/tutorials/05_physics/viz_wrecking_ball.py
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_utils.py
Labels: type:Maintenance

#292 Disable VTK Warnings on release version
  fury/__init__.py
Labels: type:Maintenance

#288 Shader manager
  .codecov.yml
  docs/tutorials/04_shaders/viz_shader.py
  fury/actor.py
  fury/shaders/__init__.py
  fury/shaders/base.py
  fury/shaders/billboard_dec.frag
  fury/shaders/billboard_dec.vert
  fury/shaders/billboard_impl.vert
  fury/shaders/tests/__init__.py
  fury/shaders/tests/test_base.py
  fury/tests/test_actors.py
Labels: type:New Feature

#290 Release 0.6.1 preparation
  .mailmap
  AUTHORS.rst
  docs/source/posts/2020/2020-06-07-week-2-lenix.rst
  docs/source/posts/2020/2020-06-28-week-5-soham.rst
  docs/source/posts/2020/2020-08-02-week-10-soham.rst
  docs/source/posts/2020/2020-08-18-release-announcement.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.6.1.rst
  docs/tutorials/02_ui/viz_radio_buttons.py
  docs/tutorials/05_physics/README.rst
  fury/deprecator.py
Labels: type:Release Plan

#295 Update fetcher
  fury/data/fetcher.py
Labels: type:Enhancement

#303 FIX vtp reader
  fury/io.py
Labels: type:Bug Fix

#302 moved physics tutorials to examples under the heading 'Integrate physics using pybullet'
  docs/examples/physics_using_pybullet/README.rst
  docs/examples/physics_using_pybullet/viz_ball_collide.py
  docs/examples/physics_using_pybullet/viz_brick_wall.py
  docs/examples/physics_using_pybullet/viz_chain.py
  docs/examples/physics_using_pybullet/viz_wrecking_ball.py
  docs/tutorials/05_physics/README.rst
  requirements/docs.txt
Labels: type:Documentation
