Repository fury-gl/fury, pull requests merged in 2021-06, with the labels that each got.

#356 Render a video on an actor.
  docs/examples/viz_play_video.py
  fury/actor.py
  fury/tests/test_actors.py
  requirements/docs.txt
Labels: type:Documentation, type:New Feature

#440 added support for URL image in ImageContainer2D
  fury/io.py
  fury/tests/test_io.py
  fury/ui.py
Labels: type:Enhancement

#444 Remove deprecated functions
  fury/actor.py
  fury/window.py
Labels: type:Maintenance

#422 This allow to draw markers using shaders
  docs/examples/viz_markers.py
  fury/actor.py
  fury/shaders/billboard_dec.frag
  fury/shaders/billboard_spheres_impl.frag
  fury/shaders/marker_billboard_dec.frag
  fury/shaders/marker_billboard_dec.vert
  fury/shaders/marker_billboard_impl.frag
  fury/shaders/marker_billboard_impl.vert
  fury/tests/test_actors.py
Labels: type:New Feature

#420 added an example about graph-tool and nested stochastic block model
  docs/examples/viz_nested_block_model.py
Labels: type:Documentation

#438 Fast selection of multiple objects in 3D using GPU acceleration
  docs/tutorials/01_introductory/viz_selection.py
  fury/actor.py
  fury/data/files/selector_actors.log.gz
  fury/data/files/selector_faces.log.gz
  fury/data/files/selector_vertices.log.gz
  fury/pick.py
  fury/tests/test_pick.py
  fury/window.py
Labels: type:New Feature
