Repository fury-gl/fury, pull requests merged in 2021-02, with the labels that each got.

#373 Updated actor.py
  fury/actor.py
Labels: type:Documentation

#374 ENH: Refactor actor.odf_slicer for increased performances
  docs/examples/viz_fiber_odf.py
  fury/actor.py
  fury/actors/__init__.py
  fury/actors/odf_slicer.py
  fury/data/__init__.py
  fury/data/fetcher.py
  fury/tests/test_actors.py
  fury/utils.py
Labels: type:Enhancement

#376 Added animations for some electromagnetic phenomena
  docs/examples/viz_emwave_animation.py
  docs/examples/viz_helical_motion.py
Labels: type:Documentation

#383 Minor documentation fix
  docs/tutorials/03_shaders/viz_shader.py
Labels: type:Documentation

#387 [fix] Propagate update_actor
  README.md
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:Enhancement

#385 fixed the example for superquadric function
  fury/actor.py
Labels: type:Documentation, type:Enhancement
