Repository fury-gl/fury, pull requests merged in 2021-04, with the labels that each got.

#405 Updating Redirecting Issues in Readme
  README.md
Labels: type:Maintenance

#406 Removed unused library in FURY tutorial
  docs/examples/viz_network_animated.py
Labels: type:Maintenance

#371 Textbox2d special character support
  fury/data/files/test_ui_textbox.json
  fury/data/files/test_ui_textbox.log.gz
  fury/interactor.py
  fury/ui.py
Labels: type:Enhancement

#412 fix paper doi
  paper.bib
  paper.md
Labels: type:Documentation

#426 Allows to define the priority of a shader_callback and obtain the vtkEventId
  fury/shaders/base.py
  fury/tests/test_shaders.py
Labels: type:Enhancement
