Repository fury-gl/fury, pull requests merged in 2021-03, with the labels that each got.

#370 Materials module including Physically Based Rendering (PBR)
  fury/material.py
  fury/tests/test_material.py
Labels: type:New Feature

#389 ENH: peaks_slicer option for asymmetric peaks visualization
  fury/actor.py
  fury/tests/test_actors.py
Labels: type:Enhancement

#392 Release 0.7.0 preparation
  .mailmap
  AUTHORS.rst
  LICENSE
  ci/travis/script.sh
  docs/examples/viz_brownian_motion.py
  docs/examples/viz_helical_motion.py
  docs/source/ext/github_tools.py
  docs/source/posts/2021/2021-03-09-gsoc.rst
  docs/source/posts/2021/2021-03-13-release-announcement.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.7.0.rst
  fury/tests/test_actors.py
  fury/tests/test_material.py
  requirements/test.txt
Labels: type:Maintenance, type:Release Plan

#393 added primitive and actor for triangular prism, added tests too
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#399 Resolve warnings #317 & and Fix Issue: #355
  docs/source/ext/github_tools.py
  fury/tests/test_actors.py
  fury/tests/test_convert.py
  fury/tests/test_utils.py
  fury/window.py
Labels: type:Maintenance
