Repository fury-gl/fury, pull requests merged in 2021-09, with the labels that each got.

#474 Add primitive and actor for pentagonal prism with test
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#449 Add python3.9 for our CI's
  .github/workflows/test.yml
  azure-pipelines.yml
Labels: type:Maintenance

#488 Fix material docstrings, improved standard parameters and improved materials application support
  fury/material.py
  fury/tests/test_material.py
Labels: type:Bug Fix

#496 Added GSoC blog posts for remaining weeks
  docs/source/posts/2021/2021-08-02-week-9-antriksh.rst
  docs/source/posts/2021/2021-08-09-week-10-antriksh.rst
  docs/source/posts/2021/2021-08-16-week-11-antriksh.rst
  docs/source/posts/2021/2021-08-23-final-work-antriksh.rst
Labels: type:Documentation

#491 Method to process and load sprite sheets
  fury/io.py
  fury/tests/test_io.py
Labels: type:New Feature

#470 Update the way we import external libraries by using only the necessary modules
  fury/__init__.py
  fury/actor.py
  fury/actors/odf_slicer.py
  fury/actors/peak.py
  fury/actors/tests/test_peak.py
  fury/colormap.py
  fury/convert.py
  fury/interactor.py
  fury/io.py
  fury/lib.py
  fury/material.py
  fury/pick.py
  fury/primitive.py
  fury/shaders/base.py
  fury/shaders/tests/test_base.py
  fury/testing.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_io.py
  fury/tests/test_material.py
  fury/tests/test_shaders.py
  fury/tests/test_testing.py
  fury/tests/test_utils.py
  fury/ui/containers.py
  fury/ui/core.py
  fury/utils.py
  fury/window.py
Labels: type:Enhancement
