Repository fury-gl/fury, pull requests merged in 2021-07, with the labels that each got.

#459 extracted Button2D class from `elements` to `core`
  fury/ui/core.py
  fury/ui/elements.py
  fury/ui/tests/test_core.py
  fury/ui/tests/test_elements.py
Labels: type:Maintenance

#441 Added border support in Panel2D
  fury/ui/containers.py
  fury/ui/tests/test_core.py
Labels: type:Enhancement

#442 added method to wrap overflowing text
  fury/ui/helpers.py
  fury/ui/tests/test_helpers.py
Labels: type:Enhancement

#477 added blog posts for GSoC'21
  docs/source/posts/2021/2021-06-08-week-1-antriksh.rst
  docs/source/posts/2021/2021-06-13-week-2-antriksh.rst
  docs/source/posts/2021/2021-06-21-week-3-antriksh.rst
  docs/source/posts/2021/2021-06-28-week-4-antriksh.rst
  docs/source/posts/2021/2021-07-05-week-5-antriksh.rst
  docs/source/posts/2021/2021-07-12-week-6-antriksh.rst
  docs/source/posts/2021/2021-07-19-week-7-antriksh.rst
  docs/source/posts/2021/2021-07-26-week-8-antriksh.rst
Labels: type:Documentation

#476 Google Summer of Code blog posts
  docs/source/posts/2021/2021-06-08-gsoc-devmessias-1.rst
  docs/source/posts/2021/2021-06-12-gsoc-devmessias-2.rst
  docs/source/posts/2021/2021-06-21-gsoc-devmessias-3.rst
  docs/source/posts/2021/2021-06-28-gsoc-devmessias-4.rst
  docs/source/posts/2021/2021-07-05-gsoc-devmessias-5.rst
  docs/source/posts/2021/2021-07-12-gsoc-devmessias-6.rst
  docs/source/posts/2021/2021-07-19-gsoc-devmessias-7.rst
  docs/source/posts/2021/2021-07-26-gsoc-devmessias-8.rst
  fury/shaders/base.py
Labels: type:Documentation
