Repository fury-gl/fury, pull requests merged in 2021-08, with the labels that each got.

#482 Release 0.7.1 preparation
  .mailmap
  docs/source/posts/2021/2021-08-03-release-announcement.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.7.1.rst
Labels: type:Release Plan

#480 Added Horizontal Layout to `layout` module
  fury/layout.py
  fury/tests/test_layout.py
Labels: type:New Feature

#479 Added Vertical Layout to `layout` module
  fury/layout.py
  fury/tests/test_layout.py
Labels: type:New Feature

#432 Fine-tuning of the OpenGL state
  docs/examples/viz_fine_tuning_gl_context.py
  fury/shaders/__init__.py
  fury/shaders/base.py
  fury/tests/test_window.py
  fury/utils.py
  fury/window.py
Labels: type:New Feature

#362 Animated Surfaces
  docs/examples/viz_animated_surfaces.py
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:Documentation
