Repository fury-gl/fury, pull requests merged in 2022-10, with the labels that each got.

#667 [WIP] Remove initialize call from multiple places
  .gitignore
  docs/examples/collision-particles.py
  docs/examples/physics_using_pybullet/viz_ball_collide.py
  docs/examples/physics_using_pybullet/viz_brick_wall.py
  docs/examples/physics_using_pybullet/viz_chain.py
  docs/examples/physics_using_pybullet/viz_domino.py
  docs/examples/physics_using_pybullet/viz_wrecking_ball.py
  docs/examples/viz_advanced.py
  docs/examples/viz_animated_surfaces.py
  docs/examples/viz_brownian_motion.py
  docs/examples/viz_emwave_animation.py
  docs/examples/viz_fiber_odf.py
  docs/examples/viz_fine_tuning_gl_context.py
  docs/examples/viz_helical_motion.py
  docs/examples/viz_network_animated.py
  docs/examples/viz_pbr_interactive.py
  docs/examples/viz_play_video.py
  docs/examples/viz_tesseract.py
  docs/experimental/viz_brick_wall.py
  docs/experimental/viz_canvas.py
  docs/experimental/viz_multisdf.py
  docs/experimental/viz_shader_canvas_sk.py
  docs/experimental/viz_shader_parallax_truchet.py
  docs/experimental/viz_shader_sines_1.py
  docs/experimental/viz_shader_square.py
  docs/experimental/viz_shader_wave.py
  docs/tutorials/01_introductory/viz_earth_animation.py
  docs/tutorials/01_introductory/viz_earth_coordinates.py
  docs/tutorials/01_introductory/viz_picking.py
  docs/tutorials/01_introductory/viz_selection.py
  docs/tutorials/01_introductory/viz_slice.py
  docs/tutorials/01_introductory/viz_solar_system.py
  docs/tutorials/01_introductory/viz_spiky.py
  docs/tutorials/01_introductory/viz_timers.py
  docs/tutorials/03_shaders/viz_shader.py
  docs/tutorials/04_stream/viz_interaction.py
  docs/tutorials/04_stream/viz_no_interaction.py
  docs/tutorials/05_animation/viz_animation_using_time_equations.py
  docs/tutorials/05_animation/viz_keyframe_animation_introduction.py
  docs/tutorials/05_animation/viz_keyframe_bezier_interpolator.py
  docs/tutorials/05_animation/viz_keyframe_camera_animation.py
  docs/tutorials/05_animation/viz_keyframe_color_interpolators.py
  docs/tutorials/05_animation/viz_keyframe_custom_interpolator.py
  docs/tutorials/05_animation/viz_keyframe_spline_interpolator.py
  fury/colormap.py
  fury/shaders/tests/test_base.py
  fury/tests/test_actors.py
  fury/tests/test_pick.py
  fury/tests/test_stream.py
  fury/tests/test_testing.py
  fury/tests/test_utils.py
  fury/tests/test_window.py
  fury/ui/tests/test_containers.py
  fury/ui/tests/test_elements.py
  fury/ui/tests/test_elements_callback.py
  fury/utils.py
  fury/window.py
  requirements/default.txt
  requirements/docs.txt
  requirements/optional.txt
Labels: type:Maintenance

#698 Added blog post for week 14
  docs/source/posts/2022/2022-09-28-week-14-mohamed.rst
Labels: type:Documentation

#699 Adding Week 16 Blogpost
  docs/source/posts/2022/2022-09-21-week-16-praneeth.rst
Labels: type:Documentation

#685 glTF skinning animation implementation
  docs/tutorials/01_introductory/viz_skinning.py
  fury/gltf.py
  fury/tests/test_gltf.py
Labels: type:New Feature

#693 Adding Week 15 Blogpost
  docs/source/posts/2022/2022-09-14-week-15-praneeth.rst
Labels: type:Documentation

#697 Adding week 14 blog
  docs/source/posts/2022/2022-09-28-week-14-shivam.rst
Labels: type:Documentation

#700 Adding morphing support in `gltf.py`
  docs/tutorials/01_introductory/viz_morphing.py
  fury/gltf.py
  fury/tests/test_gltf.py
Labels: type:New Feature
