Repository fury-gl/fury, pull requests merged in 2022-08, with the labels that each got.

#649 Added week 7 blog post
  docs/source/posts/2022/2022-08-01-week-7-mohamed.rst
Labels: type:Documentation

#648 Adding week 7 blog post
  docs/source/posts/2022/2022-08-01-week-7-shivam.rst
Labels: type:Documentation

#655 Fix test skybox
  fury/tests/test_window.py
Labels: type:Maintenance

#650 Adding Week 8 Blogpost
  docs/source/posts/2022/2022-07-27-week-8-praneeth.rst
Labels: type:Documentation

#659 Adding week 8 blog post
  docs/source/posts/2022/2022-08-09-week-08-shivam.rst
Labels: type:Documentation

#654 Adding Week 9 Blogpost
  docs/source/posts/2022/2022-08-03-week-9-praneeth.rst
Labels: type:Documentation

#662 Week 9 blog post
  docs/source/posts/2022/2022-08-16-week-9-mohamed.rst
Labels: type:Documentation

#656 Week 8 blog post
  docs/source/posts/2022/2022-08-09-week-8-mohamed.rst
Labels: type:Documentation

#663 Adding week 9 blog post
  docs/source/posts/2022/2022-08-17-week-09-shivam.rst
Labels: type:Documentation

#630 Adding function to export scenes as glTF
  docs/tutorials/01_introductory/viz_gltf_export.py
  fury/gltf.py
  fury/tests/test_gltf.py
Labels: type:New Feature

#620 Tutorial on making a primitive using polygons and SDF
  docs/tutorials/03_shaders/viz_sdf_cylinder.py
  fury/shaders/lighting/blinn_phong_model.frag
  fury/shaders/ray_marching/cast_ray.frag
  fury/shaders/sdf/central_diffs.frag
  fury/shaders/sdf/sd_cylinder.frag
  fury/shaders/utils/vec_to_vec_rot_mat.glsl
Labels: type:Documentation

#669 Added blog post for week 10
  docs/source/posts/2022/2022-08-23-week-10-mohamed.rst
Labels: type:Documentation

#666 Adding Week 10 Blogpost
  docs/source/posts/2022/2022-08-10-week-10-praneeth.rst
Labels: type:Documentation

#670 Adding week 10 blog post
  docs/source/posts/2022/2022-08-25-week-10-shivam.rst
Labels: type:Documentation

#623 DrawPanel Feature: Adding Rotation of shape from Center
  fury/data/files/test_ui_draw_panel.json
  fury/data/files/test_ui_draw_panel.log.gz
  fury/ui/elements.py
  fury/ui/tests/test_elements.py
Labels: type:New Feature
