Repository fury-gl/fury, pull requests merged in 2022-01, with the labels that each got.

#518 Pytest patch
  .github/workflows/test.yml
  azure-pipelines.yml
  ci/travis/script.sh
  ci/windows/script.ps1
  fury/data/fetcher.py
  fury/data/files/test_ui_checkbox_initial_state.log.gz
  fury/interactor.py
  fury/tests/test_material.py
  fury/tests/test_pick.py
  fury/ui/tests/test_containers.py
  fury/ui/tests/test_elements.py
  fury/window.py
  test_platform.sh
Labels: type:Maintenance

#520 Added rotation along the axis in Solar System Animations example
  docs/tutorials/01_introductory/viz_solar_system.py
Labels: type:Enhancement

#521 Snapshot flipping bug fix
  fury/io.py
  fury/tests/test_io.py
  fury/window.py
Labels: type:Bug Fix

#524 [WIP] Add debugging CI Tools
  .github/workflows/test.yml
  README.md
Labels: type:Maintenance

#509 adding `numpy_to_vtk_image_data` method to utility
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:New Feature

#527 [FIX] Allow sphere actor to use faces/vertices without casting issues. In addition, update versioning system (versioneer).
  .github/workflows/test.yml
  docs/source/ext/build_modref_templates.py
  docs/source/ext/github_tools.py
  fury/_version.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/utils.py
  requirements/default.txt
  setup.py
  versioneer.py
Labels: type:Bug Fix

#534 [FIX] remove update_user_matrix from text3d
  fury/actor.py
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:Maintenance

#536 Remove VTK_9_PLUS flag
  fury/actors/peak.py
  fury/lib.py
  fury/material.py
  fury/shaders/base.py
  fury/tests/test_actors.py
  fury/tests/test_deprecator.py
  fury/tests/test_material.py
  fury/utils.py
Labels: type:Maintenance

#538 Release preparation 0.8.0
  .mailmap
  AUTHORS.rst
  LICENSE
  docs/examples/viz_pbr_interactive.py
  docs/examples/viz_play_video.py
  docs/source/posts/2022/2022-01-31-release-announcement.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.8.0.rst
  docs/tutorials/03_shaders/viz_pbr_spheres.py
  docs/tutorials/03_shaders/viz_principled_spheres.py
  fury/actor.py
Labels: type:Release Plan
