Repository fury-gl/fury, pull requests merged in 2022-07, with the labels that each got.

#607 Adding Week 2 Blog Post
  docs/source/posts/2022/2022-06-15-week-2-praneeth.rst
Labels: type:Documentation

#615 Added blog post for week 2
  docs/source/posts/2022/2022-06-08-week-1-mohamed.rst
  docs/source/posts/2022/2022-06-28-week-2-mohamed.rst
Labels: type:Documentation

#614 Added week 2 blog
  docs/source/posts/2022/2022-06-29-week2_blog.rst
Labels: type:Documentation

#611 Adding Week 3 BlogPost
  docs/source/posts/2022/2022-06-22-week-3-praneeth.rst
Labels: type:Documentation

#616 Fixing API limits reached issue in gltf fetcher
  fury/data/fetcher.py
  fury/data/files/KhronosGltfSamples.json
  fury/data/tests/test_fetcher.py
Labels: type:Bug Fix

#621 Adding Week 4 Blogpost
  docs/source/posts/2022/2022-06-29-week-4-praneeth.rst
Labels: type:Documentation

#622 Adding week 3 blog post
  docs/source/posts/2022/2022-06-29-week2-shivam.rst
  docs/source/posts/2022/2022-07-04-week3-shivam.rst
Labels: type:Documentation

#600 Adding support for importing simple glTF files
  docs/tutorials/01_introductory/viz_gltf.py
  fury/data/fetcher.py
  fury/gltf.py
  fury/io.py
  fury/lib.py
  fury/tests/test_gltf.py
  fury/tests/test_transform.py
  fury/tests/test_utils.py
  fury/transform.py
  fury/utils.py
  requirements/default.txt
Labels: type:Enhancement

#625 Added week 4 blog post
  docs/source/posts/2022/2022-07-11-week-4-mohamed.rst
Labels: type:Documentation

#617 Added primitives count to the the Actor's polydata
  fury/actor.py
  fury/tests/test_actors.py
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:Enhancement

#610 Add DPI support for window snapshots
  fury/io.py
  fury/tests/test_io.py
  fury/window.py
Labels: type:Enhancement

#632 Bugfix: Visibility issues with ListBox2D
  fury/ui/elements.py
  fury/ui/tests/test_elements.py
Labels: type:Bug Fix

#634 Prevented calling `on_change` when slider value is set without user intervention
  fury/data/files/test_ui_line_double_slider_2d_hooks.json
  fury/data/files/test_ui_line_double_slider_2d_hooks.log.gz
  fury/data/files/test_ui_line_slider_2d_hooks.json
  fury/data/files/test_ui_line_slider_2d_hooks.log.gz
  fury/data/files/test_ui_ring_slider_2d_hooks.json
  fury/data/files/test_ui_ring_slider_2d_hooks.log.gz
  fury/ui/elements.py
  fury/ui/tests/test_elements.py
Labels: type:Enhancement

#639 Migrate Windows from Azure to GHA
  .github/workflows/test.yml
  ci/activate_env.sh
  ci/azure-pipelines.yml.old
  ci/install.sh
  ci/install_dependencies.sh
  ci/run_tests.sh
  ci/setup_headless.sh
  docs/source/_static/versions.json
  docs/source/_static/versions_switcher.json
  docs/source/_templates/custom-navbar.html
  docs/source/_templates/home.html
  docs/source/conf.py
  fury/_version.py
  fury/tests/test_actors.py
  fury/tests/test_interactor.py
  fury/tests/test_window.py
  fury/ui/tests/test_containers.py
  versioneer.py
Labels: type:Maintenance

#638 Adding Week 6 Blogpost
  docs/source/posts/2022/2022-07-13-week-6-praneeth.rst
Labels: type:Documentation

#644 Adding week 6 blog post
  docs/source/posts/2022/2022-07-25-week-6-shivam.rst
Labels: type:Documentation

#641 Week 6 blog post
  docs/source/posts/2022/2022-07-25-week-6-mohamed.rst
Labels: type:Documentation
