Repository fury-gl/fury, pull requests merged in 2022-04, with the labels that each got.

#564 Record should not make the window appear
  fury/window.py
Labels: type:Maintenance

#559 Added simulation for Tesseract
  docs/examples/viz_tesseract.py
Labels: type:Documentation

#566 Update Website Footer
  docs/source/_static/css/main.css
  docs/source/_static/images/suzanne.png
  docs/source/_templates/home.html
  docs/source/conf.py
  docs/source/getting_started.rst
Labels: type:Documentation

#569 Add new example/demo: three-dimensional fractals
  docs/examples/viz_fractals.py
Labels: type:Documentation

#547 Cone actor uses `repeat_primitive` by default
  docs/tutorials/01_introductory/viz_cone.py
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
Labels: type:New Feature

#533 Sphere actor uses repeat_primitive by default
  docs/tutorials/01_introductory/viz_sphere.py
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actors.py
  fury/tests/test_primitive.py
  fury/tests/test_window.py
Labels: type:Enhancement

#574 symmetric parameter for peak
  fury/actor.py
  fury/actors/peak.py
  fury/actors/tests/test_peak.py
Labels: type:Enhancement

#580 Update website
  docs/source/_static/images/physical.gif
  docs/source/_static/vendor/sphinx-footer.css
  docs/source/_static/vendor/styles.css
  docs/source/_templates/custom-footer.html
  docs/source/_templates/home.html
  docs/source/_templates/page.html
  docs/source/conf.py
  docs/source/index.rst
  docs/source/posts/2022/2022-02-01-gsoc.rst
Labels: type:Documentation
