Repository fury-gl/fury, pull requests merged in 2022-09, with the labels that each got.

#671 Adding Week 11 Blogpost
  docs/source/posts/2022/2022-08-17-week-11-praneeth.rst
Labels: type:Documentation

#675 Week 11 blog post
  docs/source/posts/2022/2022-08-30-week-11-mohamed.rst
Labels: type:Documentation

#674 DrawPanel Update: Seperating tests to test individual features
  fury/data/files/test_ui_draw_panel.json
  fury/data/files/test_ui_draw_panel.log.gz
  fury/data/files/test_ui_draw_panel_basic.json
  fury/data/files/test_ui_draw_panel_basic.log.gz
  fury/data/files/test_ui_draw_panel_rotation.json
  fury/data/files/test_ui_draw_panel_rotation.log.gz
  fury/ui/tests/test_elements.py
Labels: type:Maintenance

#661 Fixed `vector_text` not following camera
  fury/actor.py
  fury/lib.py
  fury/tests/test_actors.py
Labels: type:Enhancement

#672 Adding Week 12 Blogpost
  docs/source/posts/2022/2022-08-24-week-12-praneeth.rst
Labels: type:Documentation

#681 Added blog post for week 12
  docs/source/posts/2022/2022-09-7-week-12-mohamed.rst
Labels: type:Documentation

#682 Adding week 12 blog post
  docs/source/posts/2022/2022-09-08-week-12-shivam.rst
Labels: type:Documentation

#683 Adding Week 13 Blogpost
  docs/source/posts/2022/2022-08-31-week-13-praneeth.rst
Labels: type:Documentation

#691 Added week 13 post
  docs/source/posts/2022/2022-09-20-week-13-mohamed.rst
Labels: type:Documentation

#686 Adding week 13 blog post
  docs/source/posts/2022/2022-09-15-week-13-blog.rst
Labels: type:Documentation

#665 Timeline hierarchical transformation and fixing some issues
  docs/tutorials/05_animation/README.rst
  docs/tutorials/05_animation/viz_keyframe_animation_introduction.py
  docs/tutorials/05_animation/viz_keyframe_bezier_interpolator.py
  docs/tutorials/05_animation/viz_keyframe_camera_animation.py
  docs/tutorials/05_animation/viz_keyframe_color_interpolators.py
  docs/tutorials/05_animation/viz_robot_arm_animation.py
  fury/animation/tests/test_timeline.py
  fury/animation/timeline.py
  fury/tests/test_utils.py
  fury/utils.py
Labels: type:Enhancement

#643 [WIP] Adding ability to load glTF animations
  docs/tutorials/01_introductory/viz_gltf_animated.py
  fury/animation/interpolator.py
  fury/gltf.py
  fury/tests/test_gltf.py
  fury/tests/test_transform.py
  fury/transform.py
Labels: type:Documentation

#689 GLTF actor colors from material
  docs/tutorials/01_introductory/viz_gltf.py
  fury/gltf.py
  fury/tests/test_gltf.py
  fury/tests/test_transform.py
  fury/transform.py
Labels: type:Enhancement
