Repository fury-gl/fury, pull requests merged in 2023-06, with the labels that each got.

#788 Adding Week0 Blogpost
  docs/source/posts/2023/2023-06-02-week-0-praneeth.rst
Labels: type:Documentation

#789 Added blogpost week 0
  docs/source/posts/2023/2023-06-02-week-0-tvcastillod.rst
Labels: type:Documentation

#797 Week 1 blogpost
  docs/source/posts/2023/2023-06-05-week-1-joaodellagli.rst
Labels: type:Documentation

#768 Overload set_visibility for Panel2D and Combobox2D
  fury/ui/containers.py
  fury/ui/elements.py
  fury/ui/tests/test_elements.py
Labels: category: UI

#798 Added blogpost week 1
  docs/source/posts/2023/2023-06-05-week-1-tvcastillod.rst
Labels: type:Documentation

#799 Adding Week2 BlogPost
  docs/source/posts/2023/2023-06-11-week-2-praneeth.rst
Labels: type:Documentation

#802 Added blogpost week 2
  docs/source/posts/2023/2023-06-12-week-2-tvcastillod.rst
Labels: type:Documentation

#800 Week2 Blogpost
  docs/source/posts/2023/2023-06-12-week-2-joaodellagli.rst
Labels: type:Documentation

#398 feat: added a Card2D widget to UI
  docs/examples/_valid_examples.toml
  docs/examples/viz_card.py
  docs/examples/viz_card_sprite_sheet.py
  fury/data/files/test_card_ui.json
  fury/data/files/test_card_ui.log.gz
  fury/ui/elements.py
  fury/ui/tests/test_elements.py
Labels: type:New Feature, category: UI

#805 GSoC: Adding Week3 Blogpost
  docs/source/posts/2023/2023-06-17-week-3-praneeth.rst
Labels: type:Documentation

#806 Week 3 Blogpost
  docs/source/posts/2023/2023-06-19-week-3-joaodellagli.rst
Labels: type:Documentation

#807 Added blogpost week 3
  docs/source/posts/2023/2023-06-19-week-3-tvcastillod.rst
Labels: type:Documentation

#809 Week 4 Blogpost
  docs/source/posts/2023/2023-06-26-week-4-joaodellagli.rst
Labels: type:Documentation

#811 GSoC: Adding Week 4 Blogpost
  docs/source/posts/2023/2023-06-24-week-4-praneeth.rst
Labels: type:Documentation
