Repository fury-gl/fury, pull requests merged in 2023-04, with the labels that each got.

#766 Cylinder repeat primitive
  fury/actor.py
  fury/primitive.py
Labels: type:Enhancement

#771 add one condition in `repeat_primitive` to handle direction [-1, 0, 0], issue #770
  fury/primitive.py
  fury/tests/test_primitive.py
Labels: type:Bug Fix

#777 Remove alias keyword on documentation
  docs/source/ext/apigen.py
  fury/lib.py
Labels: type:Documentation

#778 TabUI collapsing/expanding improvements
  fury/ui/containers.py
Labels: type:Enhancement

#784 Peak fix in Nvidia GPUs
  fury/actors/peak.py
Labels: type:Bug Fix
