Repository fury-gl/fury, pull requests merged in 2023-02, with the labels that each got.

#726 Adding GSoC'22 Final Report
  docs/source/posts/2022/2023-01-24-final-report-praneeth.rst
Labels: type:Documentation

#737 remove object keyword from class
  docs/source/ext/apigen.py
  docs/source/ext/scrap.py
  fury/actor.py
  fury/interactor.py
  fury/layout.py
  fury/optpkg.py
  fury/shaders/tests/test_base.py
  fury/testing.py
  fury/ui/tests/test_elements_callback.py
  fury/window.py
Labels: type:Maintenance

#739 added a check for operating system before executing the tput command through popen in fury/data/fetcher.py update_progressbar() function
  fury/data/fetcher.py
Labels: type:Bug Fix

#478 Resolving GridUI caption error
  fury/tests/test_actors.py
  fury/ui/containers.py
  fury/ui/tests/test_containers.py
Labels: type:Bug Fix

#736 Adding GSoC'22 final report
  docs/source/posts/2022/2023-02-01-final-report-shivam.rst
Labels: type:Documentation

#734 Added GSoC'22 Final Report
  docs/source/posts/2023/2023-01-31-final-report-mohamed.rst
  fury/animation/tests/fares
Labels: type:Documentation

#688 DrawPanel Update: Moving rotation_slider from `DrawShape` to `DrawPanel`
  fury/ui/elements.py
Labels: type:Enhancement

#744 Update initialize management
  fury/window.py
Labels: type:Bug Fix
