Repository fury-gl/fury, pull requests merged in 2023-03, with the labels that each got.

#747 Connected the sliders to the right directions
  docs/tutorials/02_ui/viz_ui_slider.py
Labels: type:Documentation

#764 ComboBox2D drop_down_button mouse callback was inside for loop
  fury/ui/elements.py
Labels: type:Bug Fix

#767 Update Peak actor shader
  fury/actors/peak.py
  fury/shaders/interaction/visible_cross_section.glsl
  fury/shaders/interaction/visible_range.glsl
  fury/shaders/peak_dec.frag
  fury/shaders/peak_impl.frag
  fury/shaders/peak_impl.vert
  fury/shaders/utils/orient_to_rgb.glsl
Labels: type:Enhancement
