Repository fury-gl/fury, pull requests merged in 2023-07, with the labels that each got.

#820 Updating broken links in the Scientific Domain Section
  docs/source/_templates/home.html
Labels: type:Documentation

#817 GSoC: Adding Week 5 Blogpost
  docs/source/posts/2023/2023-07-01-week-5-praneeth.rst
Labels: type:Documentation

#791 Ellipsoid actor implemented with SDF
  fury/actor.py
  fury/actors/tensor.py
  fury/tests/test_actors.py
Labels: type:New Feature

#823 GSoC: Adding Week 6 - 7 Blogpost
  docs/source/posts/2023/2023-07-08-week-6-praneeth.rst
  docs/source/posts/2023/2023-07-15-week-7-praneeth.rst
Labels: type:Documentation

#822 GSoC: Week 7 Blogpost
  docs/source/posts/2023/2023-07-17-week-7-joaodellagli.rst
Labels: type:Documentation

#827 Added blogpost week 4, 5, 6, 7
  docs/source/posts/2023/2023-06-27-week-4-tvcastillod.rst
  docs/source/posts/2023/2023-07-03-week-5-tvcastillod.rst
  docs/source/posts/2023/2023-07-10-week-6-tvcastillod.rst
  docs/source/posts/2023/2023-07-17-week-7-tvcastillod.rst
Labels: type:Documentation

#803 UI: Adding Bounding Box & Fixing Alignment issue in TextBlock2D
  fury/ui/core.py
  fury/ui/elements.py
  fury/ui/helpers.py
  fury/ui/tests/test_containers.py
  fury/ui/tests/test_core.py
  fury/ui/tests/test_helpers.py
Labels: state: needs review, category: UI

#828 GSoC: Week 8 Blogpost
  docs/source/posts/2023/2023-07-24-week-8-joaodellagli.rst
Labels: type:Documentation

#829 GSoC: Adding Week 8 Blogpost
  docs/source/posts/2023/2023-07-22-week-8-praneeth.rst
Labels: type:Documentation
