Repository fury-gl/fury, pull requests merged in 2024-07, with the labels that each got.

#911 [DOC][FIX] fix typos in blog posts
  docs/source/posts/2021/2021-08-16-week-11-antriksh.rst
  docs/source/posts/2021/2021-16-08-gsoc-devmessias-11.rst
  docs/source/posts/2022/2022-09-15-week-13-blog.rst
  docs/source/posts/2023/2023-01-29-final-report-mohamed.rst
  docs/source/posts/2023/2023-01-29-final-report-shivam.rst
  docs/source/posts/2023/2023-06-26-week-4-joaodellagli.rst
  docs/source/posts/2023/2023-06-27-week-4-tvcastillod.rst
  docs/source/posts/2023/2023-07-03-week-5-joaodellagli.rst
  docs/source/posts/2023/2023-07-10-week-6-joaodellagli.rst
  docs/source/posts/2023/2023-07-17-week-7-tvcastillod.rst
  docs/source/posts/2023/2023-07-24-week-8-joaodellagli.rst
  docs/source/posts/2023/2023-07-31-week-9-joaodellagli.rst
  docs/source/posts/2023/2023-08-14-week-11-joaodellagli.rst
  docs/source/posts/2023/2023-08-16-week-11-tvcastillod.rst
  docs/source/posts/2023/2023-08-21-joaodellagli-final-report.rst
  docs/source/posts/2023/2023-08-21-week-12-joaodellagli.rst
  docs/source/posts/2023/2023-08-24-final-report-tvcastillod.rst
  docs/source/posts/2023/2023-08-25-final-report-praneeth.rst
  docs/source/posts/2024/2024-06-26-week4-wachiou-bouraima.rst
  docs/source/posts/2024/2024-07-01-week-4-robin.rst
  docs/source/posts/2024/2024-07-01-week-5-robin.rst
Labels: type:Documentation

#907 NF: Add lazy_loader feature in FURY
  fury/__init__.py
  fury/__init__.pyi
  fury/actors/__init__.py
  fury/actors/__init__.pyi
  fury/animation/__init__.py
  fury/animation/__init__.pyi
  fury/data/__init__.py
  fury/data/__init__.pyi
  fury/shaders/__init__.py
  fury/shaders/__init__.pyi
  fury/stream/__init__.py
  fury/stream/__init__.pyi
  fury/ui/__init__.py
  fury/ui/__init__.pyi
  fury/window.py
  pyproject.toml
  requirements/default.txt
Labels: type:New Feature

#920 Release 0.11.0 Preparation
  .mailmap
  AUTHORS.rst
  CONTRIBUTING.rst
  docs/source/posts/2024/2024-07-31-release-announcement.rst
  docs/source/release-history.rst
  docs/source/release_notes/releasev0.11.0.rst
  fury/actor.py
  fury/animation/animation.py
  fury/animation/interpolator.py
  fury/colormap.py
  fury/decorators.py
  fury/optpkg.py
  fury/transform.py
  fury/utils.py
  fury/window.py
Labels: type:Release Plan
