Repository fury-gl/fury, pull requests merged in 2025-01, with the labels that each got.

#958 Adding box actor
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actor.py
  fury/tests/test_primitive.py
Labels: v2

#959 added actor for cylinder
  fury/actor.py
  fury/tests/test_actor.py
Labels: type:New Feature, v2

#964 RF: install wgpu and mesa driver for ubuntu CI's
  ci/setup_headless.sh
  fury/tests/test_actor.py
Labels: type:Maintenance, v2

#962 NF: actor_from_primitive
  fury/actor.py
Labels: type:New Feature, v2

#963 NF: Adding actor for frustum, TEST: Adding uni tests for frustum actor
  fury/actor.py
  fury/tests/test_actor.py
Labels: type:New Feature, v2
