Repository fury-gl/fury, pull requests merged in 2025-06, with the labels that each got.

#995 NF: VectorField with arrows and thick lines
  fury/actor.py
  fury/lib.py
  fury/material.py
  fury/shader.py
  fury/wgsl/vector_field_compute.wgsl
  fury/wgsl/vector_field_render.wgsl
  fury/wgsl/vector_field_thin_render.wgsl
Labels: type:New Feature, v2

#997 NF: Surface actor introduced.
  fury/actor.py
  fury/io.py
  fury/lib.py
  fury/tests/test_actor.py
  fury/tests/test_io.py
  fury/tests/test_utils.py
  fury/utils.py
Labels: state: ready-to-be-merged, type:New Feature, v2

#1000 ENH: Test cases and Tutorial for VectorField
  docs/examples/viz_vector_field.py
  fury/actor.py
  fury/material.py
  fury/tests/test_actor.py
  fury/tests/test_material.py
  fury/tests/test_shader.py
  fury/wgsl/vector_field_compute.wgsl
  fury/window.py
Labels: type:Enhancement, state: needs review, v2

#1009 NF: Spherical Harmonics for general purpose.
  .pre-commit-config.yaml
  docs/examples/_valid_examples.toml
  docs/examples/viz_spherical_harmonics.py
  fury/actor.py
  fury/geometry.py
  fury/lib.py
  fury/material.py
  fury/shader.py
  fury/tests/test_actor.py
  fury/tests/test_material.py
  fury/tests/test_shader.py
  fury/tests/test_utils.py
  fury/utils.py
  fury/wgsl/sph_glyph_compute.wgsl
  fury/wgsl/utils.wgsl
Labels: state: needs review, type:New Feature, v2

#1001 NF: Image Actor w/ Directions
  fury/actor.py
  fury/geometry.py
  fury/lib.py
  fury/material.py
  fury/tests/test_actor.py
  fury/tests/test_geometry.py
  fury/tests/test_material.py
Labels: type:New Feature, v2
