Repository fury-gl/fury, pull requests merged in 2025-07, with the labels that each got.

#1017 NF: Adding Ring Actor
  .pre-commit-config.yaml
  fury/actor/__init__.pyi
  fury/actor/planar.py
  fury/primitive.py
  fury/tests/test_actor.py
  fury/tests/test_primitive.py
Labels: v2

#1015 ENH: Update to use texture coordinates in surface
  fury/actor/surface.py
  fury/tests/test_actor.py
Labels: type:Enhancement, v2

#1019 RF: update star primitive
  fury/primitive.py
  fury/tests/test_primitive.py
Labels: type:Bug Fix, v2
