Repository fury-gl/fury, pull requests merged in 2025-04, with the labels that each got.

#977 BF: Fixed package name for jupyter_rfb
  fury/lib.py
Labels: v2

#978 Relying on `pygfx` shaders for non-shader geometries
  fury/io.py
  fury/material.py
  fury/shader.py
  fury/tests/test_shader.py
  fury/wgsl/mesh.wgsl
  requirements/default.txt
Labels: v2

#969 NF: Qt support and window test cases.
  .github/workflows/doc.yml
  .github/workflows/test.yml
  ci/setup_headless.sh
  docs/examples/viz_basic_qt.py
  docs/examples/viz_integrate_with_qt.py
  docs/examples/viz_multi_screen.py
  docs/examples/viz_show.py
  docs/examples/viz_skybox.py
  fury/__init__.pyi
  fury/lib.py
  fury/tests/test_window.py
  fury/window.py
  pyproject.toml
  requirements/optional.txt
Labels: state: ready-to-be-merged, v2

#970 NF: Adding text actor and its requirements
  fury/actor.py
  fury/geometry.py
  fury/lib.py
  fury/material.py
  fury/tests/test_actor.py
  fury/tests/test_geometry.py
  fury/tests/test_material.py
Labels: v2

#981 NF: Adding the axes actor
  fury/actor.py
  fury/tests/test_actor.py
Labels: v2

#983 Fix `line` actor colors
  fury/actor.py
  fury/geometry.py
  fury/tests/test_actor.py
  fury/tests/test_geometry.py
Labels: type:Bug Fix, v2

#989 CI: integration of numpydoc in precommit
  .pre-commit-config.yaml
  docs/source/conf.py
  docs/source/ext/apigen.py
  docs/source/ext/build_modref_templates.py
  docs/source/ext/github_tools.py
  docs/upload_to_gh-pages.py
  fury/__init__.py
  fury/actor.py
  fury/animation/__init__.py
  fury/animation/animation.py
  fury/animation/helpers.py
  fury/animation/interpolator.py
  fury/animation/timeline.py
  fury/colormap.py
  fury/convert.py
  fury/decorators.py
  fury/deprecator.py
  fury/geometry.py
  fury/io.py
  fury/lib.py
  fury/material.py
  fury/optpkg.py
  fury/pkg_info.py
  fury/primitive.py
  fury/shader.py
  fury/testing.py
  fury/tests/test_actors.py
  fury/tests/test_colormap.py
  fury/tests/test_deprecator.py
  fury/tests/test_interactor.py
  fury/tests/test_io.py
  fury/tests/test_primitive.py
  fury/tests/test_testing.py
  fury/tests/test_utils.py
  fury/tests/test_window.py
  fury/transform.py
  fury/ui/__init__.py
  fury/ui/containers.py
  fury/ui/core.py
  fury/ui/elements.py
  fury/ui/helpers.py
  fury/ui/tests/test_elements.py
  fury/utils.py
  fury/window.py
  pyproject.toml
  ruff.toml
Labels: type:Maintenance, v2

#984 NF: added `ellipsoid` actor
  fury/actor.py
  fury/tests/test_actor.py
Labels: type:New Feature, v2

#988 NF: Adding disk actor
  fury/actor.py
  fury/primitive.py
  fury/tests/test_actor.py
  fury/tests/test_primitive.py
Labels: type:New Feature, v2
